name = "MyFabricModpack"
author = "Ethan"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c7ac0df3c4305074898e0ff6b47b8414428140ed48567daf72e16a46389231a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
